### ISSUE TITLE
Getting value of current .step

### ISSUE THREAD

**Issue by Cyberduke01** [DongHoonPark/ltspice_pytool#21]
Hi, apologies for making an issue, but I have a question. 

I have a simulation which implements a .step command for different values. 

The problem is that when I plot the values in python from the raw file, even though I can get the values for each case, I would like to know how I can get the values of the current case in code.  i.e. if I step Rs from 1 to 10 Ohm, how do I know what was the value for Rs in the current case?

**Comment by donghoonpark** [comment]
Hi @Cyberduke01 
Unfortunately, there is no direct way to know that current iteration value of simulation.
Because this lib only get the value of simulation result not input or condition.

However, there is simple walk-around that I frequently use.
Just make bv source which indicates the step condition and read it on library.

Here is simple example that you can try.
![image](https://user-images.githubusercontent.com/10136375/126852476-64a0f538-8cf8-4162-aa11-c274f999f5f1.png)

I had considered about to read .asc file to get step condition and it is not technically difficult, but there is danger to use schematic (.asc) and result (.raw) pair which is not match.
So I won't add that function in this library.

Regards.

**Comment by Cyberduke01** [comment]
Hi, that is a good idea. Thank you for the answer
