### ISSUE TITLE
Bug when using .step and .op

### ISSUE THREAD

**Issue by gau-nernst** [DongHoonPark/ltspice_pytool#25]
First off, thank you for the great library!

I'm using .step to do a temperature sweep from -40 C to 120 C, and use .op to find the DC operating point at each temperature

```spice
.step temp -40 120 1
.op
```

When I use the library, data is only available from -40 C to 39 C (inclusive). Upon inspecting the code, I found out the bug is due to the code dividing data into 'cases' https://github.com/DongHoonPark/ltspice_pytool/blob/5055d50d4106d5aba473713f3a3138622c6ad4a7/ltspice/ltspice.py#L229-L232

Since 'Operating Point' mode is not available in the library, it defaults to 'Transient'. Thus the x data is with absolute value https://github.com/DongHoonPark/ltspice_pytool/blob/5055d50d4106d5aba473713f3a3138622c6ad4a7/ltspice/ltspice.py#L199-L200

Therefore when the temperature hits 40 C, it is equal to the first value (abs(-40) = 40), thus making it into a new case.

1. May I know why do we need to take absolute value of x data when the mode is 'Transient'?
2. Will you support Operating Point mode?

**Comment by donghoonpark** [comment]
I appreciate you taking the time to ask such a thoughtful question.

1. I'm not sure why a time point in the transient analysis is recorded as a negative value in LTspice, but it is. The unit test fails if I remove the code that calculates the transient x value as absolute because the results on the same simulation circuit differ.

2. Yes, I intend to. Actually, I've been using.op a lot lately as part of a worst-case analysis task at work. Within a month, it will be implemented. I recommend that you use ascii mode until then. Instead of Binary.

Regards.
