### ISSUE TITLE
Apply control

### ISSUE THREAD

**Issue by Wuerike** [DongHoonPark/ltspice_pytool#34]
Hi!

Is it possible to interact with the circuit during the simulation?

Im researching on MPPT AI based control, so Im looking a manner to be able to simulate a circuit in python and for each time step, read some values and act on control.

**Comment by donghoonpark** [comment]
Hello @Wuerike,

It would be wonderful to have the capability to simulate a complete control system in LTSpice. However, this task presents significant challenges due to the absence of a standardized control block implementation. If you're truly interested in pursuing this, I recommend exploring the [LTspiceControlLibrary](https://github.com/kanedahiroshi/LTspiceControlLibrary), a third-party library containing various control blocks. It even includes a basic current control block as an illustrative example.

In a previous project, I successfully constructed a simulation loop for a SiC traction inverter, achieving full control using above library. However, as implementation of full DNN in spice is nonsense, I suggest employing a strategy where you simulate with a small time step, then utilize Python (my library can be helpful here) to parse the results and apply AI-generated control outputs in subsequent time step simulations. This approach will likely yield more feasible and accurate results.
